name: CI/CD - FeriaBrApi

on:
  push:
    branches:
      - main   # roda quando fizer push na branch main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Setup Node.js
        uses: actions/setup-node@v
        with:
          node-version: 20  

      
      - name: Install dependencies
        run: npm install

      
      - name: Run tests
        run: npm test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy (exemplo)
        run: |
          echo "Deploy automatizado iniciado..."

